### ISSUE TITLE
Test Only?

### ISSUE THREAD

**Issue by MisterTK** [Duffney/InvokeDSC#9]
Could a switch be added test the local system only? So it would just run the test method and return the result. I would then want to capture that result and do something with it for reporting purposes.

It's a check to determine the current state vs. the desired state.

**Comment by duffney** [comment]
so are you thinking it would do a combination of test and then get target. Perhaps a verify-dscconfiguration cmdlet?

**Comment by MisterTK** [comment]
Yes, I guess it would be similar to the [POSHOrigin -Whatif](https://github.com/devblackops/POSHOrigin/wiki/Testing-Configurations) function. He's using Test-DscConfiguration cmdlet when the -Whatif switch is used.

**Comment by duffney** [comment]
adding a -whatif is an excellent idea man he's good I'll  look into added it. Of course feel free to take it on and do a PR.

**Comment by duffney** [comment]
@MisterTK I got around to adding -whatif to the Invoke-DSC cmdlet thanks for the suggestion :)
